Properties:
  welcomeMsg: Hello from default
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: test
Properties:
  welcomeMsg: Hello from test
server:
  port: 4000
---
spring:
  config:
    activate:
      on-profile: prod
Properties:
  welcomeMsg: Hello from prod
server:
  port: 5000